# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: iasc-monads
version: '0.0.0'
github: "githubuser/iasc-monads"
license: MIT
author: "Author name here"
maintainer: "Author name here"
# synopsis: A new Haskeleton package.
# description: iasc-monads is a new Haskeleton package.
# category: Other

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall

library:
  dependencies:
  - base
  source-dirs: library

executables:
  iasc-monads:
    source-dirs: executable
    main: Main.hs
    dependencies:
    - base
    - iasc-monads
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

benchmarks:
  iasc-monads-benchmarks:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
    - base
    - iasc-monads
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

tests:
  iasc-monads-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - base
    - iasc-monads
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
